---
title: "OD mapping"
author: "Conor Tompkins"
date: "September 16, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
#library(zipcode)
library(noncensus)
library(janitor)
library(lubridate)
library(gganimate)
library(sf)
library(tigris)

options(tigris_use_cache = TRUE)

theme_set(theme_minimal())
my_census_key <- "a16f3636406d2b544871e2ae49bb318c3ddcacba"
census_api_key(my_census_key)

census_vars <- load_variables(2010, "sf1", cache = TRUE)
```

```{r}
map_df(list.files("data/overdoses", full.names = TRUE), 
               read_csv, col_names = TRUE, cols(.default = "c")) -> data
```

```{r}
data %>% 
  clean_names() %>% 
  mutate(id = row_number(),
         date = mdy(death_date),
         year = year(date),
         yday = yday(date),
         month = month(date),
         mday = mday(date),
         wday = wday(date),
         incident_zip = as.character(incident_zip),
         decedent_zip = as.character(decedent_zip),
         date = ymd(str_c(year, month, sep = "-"), truncated = 1)) %>% 
  select(date, year, month, incident_zip, decedent_zip) %>% 
  filter(!is.na(incident_zip), !is.na(decedent_zip)) -> df

df %>% 
  filter(incident_zip != "1`513",
         decedent_zip != "1`513") %>% 
  count(date, incident_zip) %>% 
  complete(date, incident_zip) %>% 
  replace_na(list(n = 0)) %>% 
  spread(date, n) -> df_ods_zip

data(zip_codes)
data("counties")
counties %>% 
  filter(state == "PA",
         county_name %in% c("Allegheny County", "Washington County", 
                            "Butler County", "Westmoreland County", 
                            "Beaver County", "Armstrong County")) %>% 
  mutate(fips = str_c(state_fips, county_fips)) -> pa_fips

zip_codes %>% 
  mutate(fips = as.character(fips)) -> zip_codes

zip_codes %>% 
  semi_join(pa_fips) -> pa_zipcodes
```

```{r}
#allegheny_zipcodes <- read_csv("data/Allegheny_County_Zip_Code_Boundaries.csv") %>% 
#  mutate(zip = as.character(ZIP))
```

```{r}
#add total population variable, calculcate per capita OD
get_acs(geography = "zcta",
        #county = "Allegheny",
              variables = "B01003_001", 
              #state = "PA",
        geometry = TRUE) -> df_geo_zip

st_erase <- function(x, y) {
  st_difference(x, st_union(st_combine(y)))
}

allegheny_water <- area_water("PA", "Allegheny", class = "sf")

#df_geo_zip <- st_erase(df_geo_zip, allegheny_water)

get_acs(geography = "county",
        county = "Allegheny",
              variables = "B01003_001", 
              state = "PA",
        geometry = TRUE) -> df_geo_county
```

```{r}
(df_geo_zip %>% 
  semi_join(pa_zipcodes, by = c("GEOID" = "zip")) -> df_geo_od)

(df_geo_od %>% 
  left_join(df_ods_zip, by = c("GEOID" = "incident_zip")) -> df_geo_od)
  #complete(year, GEOID) %>% 
  #replace_na(list(n = 0)) %>% 

(df_geo_od %>% 
    gather(date, n, -c(GEOID:moe, geometry)) %>% 
    mutate(year = year(date),
           od_per_capita = (n / estimate) * 1000) -> df_geo_od)

threshhold <- 400
df_geo_od %>%
  mutate(od_per_capita = case_when(estimate <= threshhold ~ 0,
                                   estimate > threshhold ~ od_per_capita)) %>% 
  filter(year >= 2015) %>%
  group_by(GEOID, year) %>% 
  summarize(od_per_capita = sum(od_per_capita)) %>% 
  ggplot() +
  geom_sf(aes(fill = od_per_capita), size = .1, color = "grey") +
  geom_sf(data = df_geo_county, color = "red", size = 1, linetype = 1, alpha = 0) +
  scale_fill_viridis_c("Overdoses per 1,000", option = "B") +
  scale_alpha_continuous(range = c(.5, 1)) +
  coord_sf(xlim = c(-79.6, -80.4), ylim = c(40.2, 40.7)) +
  facet_wrap(~year) +
  labs(title = "Allegheny County Fatal Overdoses",
       subtitle = str_c("Zip codes with < ", threshhold, " population set to 0", "\nPopulation based on 2012-2016 ACS"),
       caption = "@conor_tompkins, data from WPRDC") +
  theme(axis.text = element_blank())
```

```{r eval = FALSE}
threshhold <- 400
df_geo_od %>%
  mutate(od_per_capita = case_when(estimate <= threshhold ~ 0,
                                   estimate > threshhold ~ od_per_capita)) %>% 
  filter(year >= 2015) %>%
  group_by(GEOID, year) %>% 
  summarize(od_per_capita = sum(od_per_capita)) %>%
  ggplot() +
  geom_sf(aes(fill = od_per_capita), size = .1, color = "grey") +
  geom_sf(data = df_geo_county, color = "red", size = 1, linetype = 1, alpha = 0) +
  scale_fill_viridis_c("Overdoses per 1,000", option = "B") +
  coord_sf(xlim = c(-79.4, -80.5), ylim = c(40.2, 40.7)) +
  labs(title = "Allegheny County Fatal Overdoses",
    subtitle = str_c("Year: {closest_state}. ", 
                     "Zip codes with < ", 
                     threshhold, 
                     " population set to 0", 
                     "\nPopulation based on 2012-2016 ACS"),
    caption = "@conor_tompkins, data from WPRDC") +
  theme(axis.text = element_blank()) +
  transition_states(year, transition_length = .5, state_length = 2) +
  ease_aes("linear") -> ani

#animate(ani, nframes = 100)
gif_ani <- animate(ani, nframes = 100)
anim_save("overdose_map.gif", animation = gif_ani)
gif_ani

```

```{r}
threshhold <- 400

df_geo_od %>%
  st_set_geometry(NULL) %>% 
  mutate(od_per_capita = case_when(estimate <= threshhold ~ 0,
                                   estimate > threshhold ~ od_per_capita)) %>% 
  group_by(GEOID, year) %>% 
  summarize(od_per_capita = sum(od_per_capita)) %>% 
  ungroup() %>% 
  filter(year >= 2015) %>% 
  arrange(GEOID, year) %>% 
  group_by(GEOID) %>% 
  mutate(cum_sum = cumsum(od_per_capita)) %>% 
  select(GEOID, year, cum_sum) -> df_cumulative

df_cumulative %>% 
  ggplot(aes(year, cum_sum, group = GEOID)) +
  geom_line() +
  transition_reveal(GEOID, year)

df_geo_od %>% 
  left_join(df_cumulative) %>% 
  filter(year >= 2015) %>%  
  ggplot() +
  geom_sf(aes(fill = cum_sum), size = .1, color = "grey") +
  geom_sf(data = df_geo_county, color = "red", size = 1, linetype = 1, alpha = 0) +
  scale_fill_viridis_c("Cumulative overdoses per 1,000", option = "B") +
  coord_sf(xlim = c(-79.4, -80.5), ylim = c(40.2, 40.7)) +
  labs(title = "Allegheny County Fatal Overdoses",
    subtitle = str_c("Year: {closest_state}. ", 
                     "Zip codes with < ", 
                     threshhold, 
                     " population set to 0", 
                     "\nPopulation based on 2012-2016 ACS"),
    caption = "@conor_tompkins, data from WPRDC") +
  theme(axis.text = element_blank()) +
  #facet_wrap(~year)
  transition_states(year, transition_length = .5, state_length = 1) +
  ease_aes("linear") -> ani

gif_ani <- animate(ani)
gif_ani
anim_save("cumulative_overdose_map.gif", animation = gif_ani)


```
