---
title: "OD factor network"
author: "Conor Tompkins"
date: "December 15, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(tidygraph)
library(ggraph)
library(tidytext)
library(widyr)
library(viridis)
library(ggrepel)

source("scripts/load_data.R")

theme_set(theme_bw(base_size = 18))
```

```{r}
df %>% 
  select(od_factors)

df %>% 
  arrange(id) %>% 
  select(id, od_factors) %>% 
  #unnest_tokens(bigram, od_factors)
  unnest_tokens(bigram, od_factors, token = stringr::str_split, pattern = ",") %>% 
  #unnest_tokens(bigram, od_factors, token = "ngrams", n = 2)
  #unnest_tokens(bigram, od_factors, token = "words")
  separate(bigram, c("word1", "word2"), sep = " ") -> test

test %>% 
  select(-id) %>% 
  count(word1, word2, sort = TRUE) -> test
  
test
```


```{r}
#not adding properly
df %>% 
  arrange(id) %>% 
  select(id, od_factors) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
  arrange(id, word) %>% 
  mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>% 
  pairwise_count(word, id, sort = TRUE, diag = FALSE) -> word_pairs

word_pairs

#word_pairs %>% 
#  group_by(item1, item2) %>% 
#  mutate(item1_lag = lag(item1),
#         item2_lag = lag(item2)) %>% 
#  mutate(item1_lag = case_when(is.na(item1_lag) ~ item1,
#                               !is.na(item1_lag) ~ item1_lag),
#         item2_lag = case_when(is.na(item2_lag) ~ item2,
#                               !is.na(item2_lag) ~ item2_lag),
#         flag = case_when(item1_lag == item1 & item2_lag == item2 ~ TRUE,
#                          item1_lag != item1 | item2_lag != item2 ~ FALSE)) %>% 
#  View()



#word_pairs %>% 
#  mutate(key1 = str_c(item1, item2, sep = ", "),
#         key2 = str_c(item2, item1, sep = ", "))
#  group_by(key2) %>% 
#  summarize(n = sum(n)) %>% 
#  arrange(desc(n))

set.seed(1234)

word_pairs %>%
  filter(n > 40) %>% 
  as_tbl_graph(directed = FALSE) %>% 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_width = n, edge_alpha = n)) +
  geom_node_point() +
  geom_node_label(aes(label = name)) +
  scale_edge_alpha_continuous("Pair count", range = c(.1, .8)) +
  scale_edge_width_continuous("Pair count", range = c(.1, 3)) +
  theme_graph()
```

```{r}
top_words <- df %>% 
  arrange(id) %>% 
  select(id, od_factors) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
    mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>%
  count(word, sort = TRUE) %>% 
  filter(!is.na(word)) %>% 
  top_n(20) %>% 
  pull(word)

df %>%
  arrange(id) %>% 
  select(id, od_factors) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
  mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>% 
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, id, sort = TRUE) -> word_corrs


word_corrs %>%
  filter(abs(correlation) > .05,
         !is.na(item1), !is.na(item2),
         item1 %in% top_words, item2 %in% top_words) %>% 
  as_tbl_graph(directed = FALSE) %>% 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_width = abs(correlation), edge_color = correlation)) +
  geom_node_point() +
  geom_node_label(aes(label = name)) +
  scale_edge_color_continuous("Correlation", low = "blue", high = "red") +
  #scale_edge_color_viridis() +
  scale_edge_width_continuous("Absolute correlation", range = c(.1, 3)) +
  theme_graph()
```

```{r}
df %>%
  filter(year == 2016) %>% 
  arrange(id) %>% 
  select(id, od_factors, year) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
  mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>% 
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, id, sort = TRUE) %>% 
  mutate(year = 2016) -> word_corrs_2016

df %>%
  filter(year == 2017) %>% 
  arrange(id) %>% 
  select(id, od_factors, year) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
  mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>% 
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, id, sort = TRUE) %>% 
  mutate(year = 2017) -> word_corrs_2017

word_corrs_years <- bind_rows(word_corrs_2016, word_corrs_2017)

set.seed(1234)

word_corrs_years %>%
  filter(abs(correlation) > .05,
         !is.na(item1), !is.na(item2),
         item1 %in% top_words, item2 %in% top_words) %>% 
  as_tbl_graph(directed = FALSE) %>% 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_width = abs(correlation), edge_color = correlation)) +
  geom_node_point() +
  geom_node_label(aes(label = name)) +
  facet_edges(~year) +
  scale_edge_color_continuous("Correlation", low = "blue", high = "red") +
  #scale_edge_color_viridis() +
  scale_edge_width_continuous("Absolute correlation", range = c(.1, 3)) +
  theme_graph()
```

```{r}
df %>% 
  filter(year == 2016) %>% 
  arrange(id) %>% 
  select(id, od_factors) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
  mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>% 
  pairwise_count(word, id, sort = TRUE, diag = FALSE) %>% 
  mutate(year = 2016) -> word_pairs_2016

df %>% 
  filter(year == 2017) %>% 
  arrange(id) %>% 
  select(id, od_factors) %>% 
  unnest_tokens(word, od_factors, token = stringr::str_split, pattern = ", ") %>% 
  mutate(word = case_when(str_detect(word, "fentanyl") ~ "fentanyl",
                          !str_detect(word, "fentanyl") ~ word)) %>% 
  pairwise_count(word, id, sort = TRUE, diag = FALSE) %>% 
  mutate(year = 2017) -> word_pairs_2017

word_pairs_years <- bind_rows(word_pairs_2016, word_pairs_2017)

word_pairs_years %>% 
  filter(n > 10) %>% 
  as_tbl_graph(directed = FALSE) %>% 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_width = n, edge_alpha = n)) +
  geom_node_point() +
  geom_node_label(aes(label = name)) +
  facet_edges(~year) +
  scale_edge_alpha_continuous("Pair count", range = c(.1, .8)) +
  scale_edge_width_continuous("Pair count", range = c(.1, 3)) +
  theme_graph()
```


```{r}
word_pairs_years %>% 
  spread(year, n) %>% 
  mutate(change = `2017` - `2016`,
         combo = str_c(item1, item2, sep = " + ")) -> test

test %>% 
  filter(`2016` > 5,
         `2017` > 5) %>% 
  ggplot(aes(`2016`, `2017`, label = combo, size = `2016` + `2017`)) +
  geom_point() +
  geom_label_repel() +
  geom_abline()



```