---
title: "od network"
author: "Conor Tompkins"
date: "September 17, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
#library(zipcode)
library(noncensus)
library(janitor)
library(lubridate)
library(ggraph)
library(tidygraph)
library(sf)

options(tigris_use_cache = TRUE)

theme_set(theme_minimal())
my_census_key <- "a16f3636406d2b544871e2ae49bb318c3ddcacba"
census_api_key(my_census_key)

census_vars <- load_variables(2010, "sf1", cache = TRUE)
```

```{r}
map_df(list.files("data/overdoses", full.names = TRUE), 
               read_csv, col_names = TRUE, cols(.default = "c")) -> data
```

```{r}
data %>% 
  clean_names() %>% 
  mutate(id = row_number(),
         #date = mdy(death_date),
         #year = year(date),
         #yday = yday(date),
         #month = month(date, label = TRUE),
         #mday = mday(date),
         #wday = wday(date),
         incident_zip = as.character(incident_zip),
         decedent_zip = as.character(decedent_zip),
         loop = (incident_zip == decedent_zip)) -> df
```

```{r}
df %>% 
  #mutate(from = decedent_zip,
  #       to = incident_zip) %>% 
  #count(from, to, sort = TRUE) %>% 
  count(decedent_zip, incident_zip, loop, sort = TRUE) -> df_graph


df_graph %>% 
  filter(loop == FALSE) %>% 
  ggplot(aes(decedent_zip, incident_zip)) +
  geom_point()
```

```{r}
df_graph %>% 
  filter(loop == FALSE,
         n > 1) %>% 
  as_tbl_graph(directed = TRUE) %>% 
  ggraph(layout = "kk") +
  geom_edge_fan(aes(edge_width = n, edge_alpha = n),
                arrow = arrow(length = unit(4, 'mm')), 
                  start_cap = circle(3, 'mm'),
                  end_cap = circle(3, 'mm')) +
  geom_node_label(aes(label = name), size = .5) +
  scale_edge_width_continuous(range = c(.3, 3)) +
  scale_edge_alpha_continuous(range = c(.3, 1))
```

```{r}
df_graph %>% 
  select(incident_zip, decedent_zip) %>% 
  gather(zip_type, zip_code) %>% 
  select(zip_code) %>% 
  distinct() -> df_zip_distinct
```

```{r}
get_acs(geography = "zcta",
        #county = "Allegheny",
              variables = "B01003_001", 
              #state = "PA",
        geometry = TRUE) %>% 
  distinct() -> df_geo_zip
```

```{r}
df_geo_zip <- cbind(df_geo_zip, st_coordinates(st_centroid(df_geo_zip)))

#df_geo_zip %>% 
#  semi_join(df_zip_distinct, by = c("GEOID" = "zip_code")) -> df_geo_zip

#df_geo_zip %>% 
#  ggplot() +
#  geom_sf() #+
  #geom_point(aes(X, Y))
```

```{r}
df_pa_zip_codes <- read_csv("data/PA zip codes.csv") %>% 
  mutate(zip_code = as.character(zip_code))
```
```{r}
df_pa_zip_codes
df_geo_zip

df_geo_zip %>% 
  right_join(df_pa_zip_codes, by = c("GEOID" = "zip_code")) %>% 
  filter(county == "Allegheny") -> df_allegheny

df_allegheny %>% 
  ggplot() +
  geom_sf() +
  geom_point(aes(X, Y))
```


```{r}
df_graph %>% 
  semi_join(df_allegheny %>% select(GEOID) %>% st_set_geometry(NULL), by = c("incident_zip" = "GEOID")) %>% 
  semi_join(df_allegheny %>% select(GEOID) %>% st_set_geometry(NULL), by = c("incident_zip" = "GEOID"))-> df_graph_allegheny

df_graph_allegheny %>% 
  distinct(incident_zip)
df_graph_allegheny %>% 
  distinct(decedent_zip)
```

```{r}
df_graph_allegheny %>% 
  select(incident_zip, decedent_zip, loop, n) %>% 
  filter(loop == FALSE) %>%  
  as_tbl_graph(directed = TRUE) -> df_network

df_network


df_network %>% 
  ggraph() +
  geom_edge_fan(aes(edge_width = n)) +
  geom_node_point()
```
```{r}
df_network
```

```{r}
node_pos <- df_allegheny %>%
  select(GEOID, X, Y) %>%
  rename(x = X, y = Y) %>%  # node positions must be called x, y
  st_set_geometry(NULL)
str(node_pos)
```
```{r}
lay <- create_layout(df_network, 'manual',
                     node.positions = node_pos)

manual_layout <- create_layout(graph = df_network,
                               layout = "manual", node.positions = node_pos)
```







```{r eval = FALSE, include = FALSE}
df_geo_zip %>% 
  st_centroid() %>% 
  st_coordinates() %>% 
  ggplot(aes(X, Y)) +
  geom_point()

sfc_as_cols <- function(x, geometry, names = c("x","y")) {
  if (missing(geometry)) {
    geometry <- sf::st_geometry(x)
  } else {
    geometry <- rlang::eval_tidy(enquo(geometry), x)
  }
  stopifnot(inherits(x,"sf") && inherits(geometry,"sfc_POINT"))
  ret <- sf::st_coordinates(geometry)
  ret <- tibble::as_tibble(ret)
  stopifnot(length(names) == ncol(ret))
  x <- x[ , !names(x) %in% names]
  ret <- setNames(ret,names)
  dplyr::bind_cols(x,ret)
}

df_geo_zip %>% 
  st_centroid() %>% 
  sfc_as_cols() %>%
  st_set_geometry(NULL) -> df_geo_zip_centroids

df_geo_zip %>% 
  right_join(df_graph, by = c("GEOID" = "incident_zip")) %>% 
  left_join(df_geo_zip_centroids) %>% 
  ggplot() +
  geom_sf() +
  geom_point(aes(x, y), size = 1)
  



```










Look at net exporter zips vs net importer

