---
title: "Presentation"
author: "Conor Tompkins"
date: "April 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(viridis)
library(ggrepel)
library(knitr)
library(kableExtra)
library(tidycensus)
library(sf)
library(tigris)
library(noncensus)

options(tigris_use_cache = TRUE)
my_census_key <- "a16f3636406d2b544871e2ae49bb318c3ddcacba"
census_api_key(my_census_key)

#use a customized version of theme_bw()
theme_set(theme_bw(base_size = 18))
```

#Identifying Trends in Overdoses in Allegheny County

```{r}
source("https://raw.githubusercontent.com/conorotompkins/allegheny_overdoses/master/scripts/load_data.R")
```

#Time series
```{r}
df %>% 
  count(date) %>% 
  mutate(n_cumsum = cumsum(n)) %>% 
  ggplot(aes(date, n_cumsum)) +
  geom_hline(yintercept = 0) +
  geom_line(size = 2) +
  scale_y_continuous(label=comma) +
  labs(title = "Fatal overdoses in Allegheny County",
       y = "Cumulative sum of fatal overdoses",
       x = "",
       subtitle = "Data from the WPRDC",
       caption = "Conor Tompkins @conor_tompkins")
```

```{r}
df %>% 
  group_by(year, yday) %>% 
  summarize(n = n()) %>% 
  mutate(n_cumsum = cumsum(n)) -> df_year_cumsum

df %>% 
  group_by(year) %>% 
  summarize(last_yday = last(yday),
            total = n()) -> df_year_tag

ggplot(data = df_year_cumsum, aes(x = yday, y = n_cumsum, color = as.factor(year))) +
  geom_line(size = 1.5) +
  geom_label_repel(data = df_year_tag, 
                   aes(x = last_yday, y = total, label = year, color = as.factor(year), group = year),
                   nudge_x = 1) +
  geom_point(data = df_year_tag, 
             aes(x = last_yday, y = total, color = as.factor(year), group = as.factor(year)), size = 3) +
  scale_size_continuous(guide = FALSE) +
  scale_color_discrete(guide = FALSE) +
  labs(title = "Fatal overdoses by year",
       x = "Day of the year",
       y = "Cumulative sum of fatal overdoses",
       subtitle = "Data from the WPRDC",
       caption = "Conor Tompkins @conor_tompkins")
```

```{r}
#create df of full calendar
df_dates <- tibble(date = seq(first(df$date), last(df$date), by = "day"))

#create tile df
df %>% 
  mutate(n = 1) %>% 
  right_join(df_dates) %>% 
  mutate(year = year(date),
         month = month(date, label = TRUE),
         mday = mday(date)) %>% 
  group_by(year, month, mday) %>% 
  summarize(n = sum(n)) %>% 
  replace_na(list(n = 0)) -> df_tile

df_tile %>% 
  ggplot(aes(mday, month, fill = n)) +
  geom_tile() +
  facet_wrap(~year, ncol = 2) +
  scale_fill_viridis("Number of fatal overdoses") +
  coord_equal() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0),
                   limits = rev(levels(df$month)),
                   breaks = c("Jan", "Apr", "Jul", "Oct")) +
  labs(title = "Fatal overdoses in Allegheny County",
       y = NULL,
       x = "Day of the month",
       subtitle = "Data from the WPRDC",
       caption = "Conor Tompkins @conor_tompkins") +
  theme(panel.grid = element_blank(),
        axis.text.y = element_text(size = 8))
```

#Drug factor
```{r}
df_factors <- df %>% 
  mutate(od_fentanyl = str_detect(od_factors, "FENTAN"),
         od_heroin = str_detect(od_factors, "HEROIN"),
         od_cocaine = str_detect(od_factors, "COCAIN"),
         od_alcohol = str_detect(od_factors, "ALCOHO"),
         od_alprazolam = str_detect(od_factors, "ALPRAZ"),
         od_oxycodone = str_detect(od_factors, "OXYCOD"),
         od_methadone = str_detect(od_factors, "METHAD"),
         od_clonazepam = str_detect(od_factors, "CLONA"),
         od_morphine = str_detect(od_factors, "MORPHI"),
         od_diazepam = str_detect(od_factors, "DIAZEP")) %>% 
  select(date, starts_with("od_"))


df_factors_long <- df_factors %>% 
  gather(od_factor, od_flag, starts_with("od_")) %>% 
  filter(od_flag == TRUE) %>% 
  mutate(od_factor = str_to_title(str_replace(od_factor, "od_", "")))

#create od_factor df
df_factors_cumsum <- df_factors_long %>% 
  group_by(od_factor, date) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  group_by(od_factor) %>% 
  mutate(od_cumsum = cumsum(n))

#create label df for od_factors
df_factors_cumsum_label <- df_factors_long %>% 
  group_by(od_factor) %>% 
  summarize(last_date = last(date),
            total = n())

#plot cumulative od_factor
ggplot(data = df_factors_cumsum, aes(x = date, y = od_cumsum, color = od_factor)) +
  geom_line(size = 1.5) +
  geom_label_repel(data = df_factors_cumsum_label, 
                   aes(x = last_date, y = total, label = od_factor, group = od_factor),
                   direction = "x", hjust = 1) +
  geom_point(data = df_factors_cumsum_label, 
             aes(x = last_date, y = total, group = od_factor, color = od_factor), size = 3) +
  scale_color_discrete(guide = FALSE) +
  scale_y_continuous(expand = c(.01, .1), label = comma) +
  labs(title = "Fatal overdoses by drug factor",
       y = "Cumulative sum of fatal overdoses",
       x = "",
       subtitle = "Data from the WPRDC",
       caption = "Conor Tompkins @conor_tompkins \n Drug overdoses not exclusive")
```

```{r message=TRUE, warning=TRUE, paged.print=TRUE}
df_factors_fentanyl <- df_factors %>% 
  #select(date, od_heroin, od_fentanyl) %>% 
  #filter(od_fentanyl) %>% 
  group_by(date) %>% 
  summarize(percent_fentanyl = mean(od_fentanyl))

df_factors_fentanyl %>% 
  ggplot(aes(date, percent_fentanyl)) +
  geom_point(alpha = .1) +
  geom_smooth(method = "glm", method.args = list(family = "binomial")) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Fatal heroin overdoses involving fentanyl",
       x = "",
       y = "% involving fentantyl",
       subtitle = "Data from the WPRDC",
       caption = "Conor Tompkins @conor_tompkins")
```

#Geographic
```{r}
df_zip <- df %>% 
  select(date, year, month, incident_zip) %>% 
  drop_na(incident_zip)

df_ods_zip <- df_zip %>% 
  filter(incident_zip != "1`513") %>% 
  count(date, incident_zip) %>% 
  complete(date, incident_zip) %>% 
  replace_na(list(n = 0)) %>% 
  spread(date, n)

data(zip_codes)
data("counties")

pa_fips <- counties %>% 
  filter(state == "PA",
         county_name %in% c("Allegheny County", "Washington County", 
                            "Butler County", "Westmoreland County", 
                            "Beaver County", "Armstrong County")) %>% 
  mutate(fips = str_c(state_fips, county_fips))

zip_codes %>% 
  mutate(fips = as.character(fips)) -> zip_codes

zip_codes %>% 
  semi_join(pa_fips) -> pa_zipcodes
```

```{r}
#allegheny_zipcodes <- read_csv("data/Allegheny_County_Zip_Code_Boundaries.csv") %>% 
#  mutate(zip = as.character(ZIP))
```

```{r}
#add total population variable, calculcate per capita OD
get_acs(geography = "zcta",
        #county = "Allegheny",
              variables = "B01003_001", 
              #state = "PA",
        geometry = TRUE) -> df_geo_zip

get_acs(geography = "county",
        county = "Allegheny",
              variables = "B01003_001", 
              state = "PA",
        geometry = TRUE) -> df_geo_county
```

```{r}
(df_geo_zip %>% 
  semi_join(pa_zipcodes, by = c("GEOID" = "zip")) -> df_geo_od)

(df_geo_od %>% 
  left_join(df_ods_zip, by = c("GEOID" = "incident_zip")) -> df_geo_od)
  #complete(year, GEOID) %>% 
  #replace_na(list(n = 0)) %>% 

(df_geo_od %>% 
    gather(date, n, -c(GEOID:moe, geometry)) %>% 
    mutate(year = year(date),
           od_per_capita = (n / estimate) * 1000) -> df_geo_od)

st_erase <- function(x, y) {
  st_difference(x, st_union(st_combine(y)))
}

allegheny_water <- area_water("PA", "Allegheny", class = "sf")

df_geo_zip <- st_erase(df_geo_zip, allegheny_water)
```
```{r}
threshhold <- 400
df_geo_od %>%
  mutate(od_per_capita = case_when(estimate <= threshhold ~ 0,
                                   estimate > threshhold ~ od_per_capita)) %>% 
  filter(year >= 2015) %>%
  na.omit() %>% 
  group_by(GEOID) %>% 
  summarize(od_per_capita = sum(od_per_capita)) %>% 
  ggplot() +
  geom_sf(aes(fill = od_per_capita), size = .1, color = "grey") +
  geom_sf(data = df_geo_county, color = "red", size = 1, linetype = 1, alpha = 0) +
  scale_fill_viridis_c("Overdoses per 1,000", option = "B") +
  scale_alpha_continuous(range = c(.5, 1)) +
  coord_sf(xlim = c(-79.6, -80.4), ylim = c(40.2, 40.7)) +
  labs(title = "Allegheny County Fatal Overdoses",
       subtitle = str_c("Zip codes with < ", threshhold, " population set to 0", "\nPopulation based on 2012-2016 ACS"),
       caption = "@conor_tompkins, data from WPRDC") +
  theme(axis.text = element_blank())
```

#Demographics
```{r}
df_demo <- df %>% 
  select(id, date, year, age, sex, race) %>%
  na.omit() %>% 
  mutate(sex = case_when(sex == "M" ~ "Male",
                         sex == "F" ~ "Female"),
         ethnicity = case_when(race == "W" ~ "White",
                          race == "B" ~ "Black",
                          race == "H" ~ "Hispanic",
                          !(race %in% c("W", "B", "H")) ~ "Other ethnicity"),
         sex_ethnicity = str_c(sex, ethnicity, sep = ", ")) %>% 
  select(-race)
```
```{r}
df_demo %>% 
  count(sex, ethnicity, sort = TRUE) %>% 
  mutate(ethnicity = fct_reorder(ethnicity, n)) %>% 
  ggplot(aes(ethnicity, n)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~sex)
```
```{r}
df_demo %>% 
  filter(ethnicity %in% c("White", "Black")) %>% 
  ggplot(aes(age, fill = ethnicity)) +
    geom_density(alpha = .75) +
    labs(title = NA,
         subtitle = NA,
         x = "Age",
         y = "",
         caption = NA) +
    scale_fill_viridis_d("Ethnicity")
```
```{r}
df_demo %>% 
  ggplot(aes(age, fill = sex)) +
  geom_density(alpha = .75) +
  labs(title = NA,
       subtitle = NA,
       x = "Age",
       y = "",
       caption = NA) +
  scale_fill_viridis_d("Sex")
```
```{r}
df_demo %>% 
  filter(ethnicity %in% c("White", "Black")) %>% 
  ggplot(aes(age, fill = sex_ethnicity)) +
  geom_density(alpha = .5) +
  facet_wrap(~sex_ethnicity, ncol = 2) +
  labs(title = NA,
       subtitle = NA,
       x = "Age",
       y = "",
       caption = NA) +
  scale_fill_viridis_d("")
```
```{r}
df_demo %>% 
  filter(ethnicity %in% c("White", "Black")) %>% 
  arrange(sex_ethnicity, date) %>% 
  count(sex_ethnicity, date) %>% 
  group_by(sex_ethnicity) %>% 
  mutate(cum_sum = cumsum(n)) -> df_demo_cumulative
```
```{r}
df_demo %>% 
  filter(ethnicity %in% c("White", "Black")) %>% 
  group_by(sex_ethnicity) %>% 
  summarize(total = n(),
            last_date = last(date)) -> df_demo_cumulative_tag
```
```{r}
#need to align labels right
ggplot(data = df_demo_cumulative, aes(x = date, y = cum_sum, color = sex_ethnicity)) +
  geom_line(size = 2) +
  geom_point(data = df_demo_cumulative_tag, 
             aes(x = last_date, y = total), size = 3) +
  geom_label_repel(data = df_demo_cumulative_tag, 
                   aes(x = last_date, y = total, color = sex_ethnicity, label = sex_ethnicity),
                  direction = "x", nudge_x = 3) +
  scale_y_continuous(label = comma) +
  scale_color_discrete(guide = FALSE) +
  labs(title = NA,
       subtitle = NA,
       x = "",
       y = "Cumulative sum of overdoses",
       caption = NA)
```
need to refactor this code
```{r}
#drug factor by category (sex, race)
df %>% 
  filter(race %in% c("W", "B")) %>% 
  mutate(od_heroin = str_detect(od_factors, "Heroin"),
         od_cocaine = str_detect(od_factors, "Cocaine"),
         od_fentanyl = str_detect(od_factors, "Fentanyl"),
         od_alcohol = str_detect(od_factors, "Alcohol"),
         od_alprazolam = str_detect(od_factors, "Alprazolam"),
         od_oxycodone = str_detect(od_factors, "Oxycodone"),
         od_morphine = str_detect(od_factors, "Morphine"),
         od_methadone = str_detect(od_factors, "Methadone"),
         od_hydrocodone = str_detect(od_factors, "Hydrocodone"),
         od_diazepam = str_detect(od_factors, "Diazepam")) -> df_factors


df_factors %>%
  mutate(category = str_c(sex, race, sep = ", ")) %>% 
  gather(od_factor, od_flag, starts_with("od_"), -category) %>% 
  filter(od_flag == TRUE) -> df_factors_long

#create od_factor df
df_factors_long %>% 
  group_by(category, od_factor, date) %>% 
  summarize(n = n()) %>% 
  group_by(category, od_factor) %>% 
  mutate(od_cumsum = cumsum(n)) -> df_factors_cumsum

#create label df for od_factors
df_factors_long %>% 
  group_by(category, od_factor) %>% 
  summarize(last_date = last(date),
            total = n()) -> df_factors_cumsum_label

#plot cumulative od_factor
ggplot(data = df_factors_cumsum, aes(x = date, y = od_cumsum, color = od_factor)) +
  geom_line(size = 1.5) +
  geom_label_repel(data = df_factors_cumsum_label, aes(x = last_date, y = total, label = str_replace(od_factor, "od_", ""), group = od_factor)) +
  geom_point(data = df_factors_cumsum_label, aes(x = last_date, y = total, group = od_factor, color = od_factor), size = 3) +
  facet_wrap(~category) +
  scale_color_discrete(guide = FALSE) +
  scale_y_continuous(expand = c(.01, .1), label = comma) +
  labs(title = NA,
       subtitle = NA,
       y = "Cumulative sum of fatal overdoses",
       caption = "Conor Tompkins, @conor_tompkins \nNot exclusive")
```